apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
   - name: myvolumes-container
     image: tomcat
     volumeMounts:
      - name: pv
        mountPath: "/usr/local/tomcat/logs"
  volumes:
   - name: pv
     persistentVolumeClaim:
       claimName: mypvc
