apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: sampleapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: sample
        image: lerndevops/samplepyapp:v1
        ports:
         - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontendsvc
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000 # inside container
    nodePort: 30001 #expose , if dont give takes default
    protocol: TCP
  selector:
    tier: frontend
